name: dart_fmt
description: Dart Formatter powered by WASM ported from dart_style
version: 0.0.0
repository: https://github.com/wasm-fmt/dart_fmt

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  dart_style: ^2.3.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
