name: dart_fmt
description: A sample command-line application.
version: 0.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  dart_style: ^2.3.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
